[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
# We must add -rpath here so that the FoundationDB client library can be dynamically linked from Postgres (/usr/local/lib/libfdb_c.dylib)
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup,-rpath,/usr/local/lib"]
